### ISSUE TITLE
other than homepage navbar user prompted to sign up or sign in

### ISSUE THREAD

**Issue by nahidahmed92** [nahidahmed92/Tech-Blog#3]
`WHEN` I click on any other links in the navigation
`THEN` I am prompted to either sign up or sign in

**Comment by zerodaydiy** [comment]
closed directly in main 
commit [4f29d2a](https://github.com/nahidahmed92/Tech-Blog/commit/4f29d2ad34a68cbbca4a015776df5f584584d9d1)
